name: Publish to NuGet

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      test_passed: ${{ steps.run_tests.outputs.test_passed }}
      coverage_passed: ${{ steps.check_coverage.outputs.coverage_passed }}
      failure_reason: ${{ steps.run_tests.outputs.failure_reason }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Create temporary NuGet.Config
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
              <packageSources>
                  <clear />
                  <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
              </packageSources>
          </configuration>' > ./nuget.config

      - name: Restore dependencies
        run: dotnet restore --configfile ./nuget.config

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Run unit tests with coverage
        id: run_tests
        run: |
          if dotnet test ToolBox.Test.Units --configuration Release --collect:"XPlat Code Coverage" --logger trx; then
            echo "test_passed=true" >> $GITHUB_OUTPUT
            echo "failure_reason=" >> $GITHUB_OUTPUT
          else
            echo "test_passed=false" >> $GITHUB_OUTPUT
            echo "failure_reason=Test failures" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Generate coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:ToolBox.Test.Units/TestResults/**/coverage.cobertura.xml -targetdir:./coverage-report

      - name: Check coverage threshold
        id: check_coverage
        run: |
          # Find the coverage report
          COVERAGE_FILE=$(find ToolBox.Test.Units/TestResults -name "coverage.json" | head -n 1)
          
          if [ -z "$COVERAGE_FILE" ]; then
            echo "No coverage report found."
            echo "coverage_passed=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          # Extract the line coverage percentage using jq
          COVERAGE=$(jq -r '.data[0].coverageSummary.lineCoverage' "$COVERAGE_FILE")
          
          if [ -z "$COVERAGE" ] || [ "$COVERAGE" = "null" ]; then
            echo "Coverage report is invalid or missing coverage data."
            echo "coverage_passed=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          echo "Code Coverage: $COVERAGE%"
          
          # Check if the code coverage meets the threshold
          if (( $(echo "$COVERAGE > 95" | bc -l) )); then
            echo "Coverage threshold met."
            echo "coverage_passed=true" >> $GITHUB_OUTPUT
          else
            echo "Coverage threshold not met."
            echo "coverage_passed=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: needs.build-and-test.outputs.test_passed == 'true' && needs.build-and-test.outputs.coverage_passed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Pack the ToolBox project
        run: dotnet pack ToolBox --configuration Release --output ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json