name: Publish to NuGet

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Create temporary NuGet.Config
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
              <packageSources>
                  <clear />
                  <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
              </packageSources>
          </configuration>' > ./nuget.config

      - name: Restore dependencies
        run: dotnet restore --configfile ./nuget.config

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Run unit tests for ToolBox.Test.Units
        run: dotnet test ToolBox.Test.Units --configuration Release --collect:"XPlat Code Coverage" --logger trx -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=json
      
      - name: Check code coverage
        id: coverage
        run: |
          # Find the coverage report
          COVERAGE_FILE=$(find ToolBox.Test.Units/TestResults -name "coverage.json" | head -n 1)
          
          if [ -z "$COVERAGE_FILE" ]; then
            echo "No coverage report found."
            echo "::set-output name=coverage_passed::false"
            exit 0
          fi
          
          # Extract the line coverage percentage
          COVERAGE=$(jq -r '.data[0].coverageSummary.lineCoverage' "$COVERAGE_FILE")
          
          echo "Code Coverage: $COVERAGE%"
          
          # Check if the code coverage meets the threshold
          if (( $(echo "$COVERAGE > 95" | bc -l) )); then
            echo "::set-output name=coverage_passed::true"
          else
            echo "::set-output name=coverage_passed::false"
          fi

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: needs.build-and-test.outputs.coverage_passed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Pack the ToolBox project
        run: dotnet pack ToolBox --configuration Release --output ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json