name: Publish to NuGet

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Create temporary NuGet.Config
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
              <packageSources>
                  <clear />
                  <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
              </packageSources>
          </configuration>' > ./nuget.config

      - name: Restore dependencies
        run: dotnet restore --configfile ./nuget.config

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Run unit tests with coverage
        run: dotnet test ToolBox.Test.Units --configuration Release --collect:"XPlat Code Coverage" --logger trx

      - name: Generate coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:./ToolBox.Test.Units/TestResults/**/coverage.cobertura.xml -targetdir:./coverage-report

      - name: Check coverage threshold
        run: |
          # Extract the line-rate from the coverage report
          LINE_RATE=$(grep -oP '(?<=<coverage line-rate=")[^"]+' ./coverage-report/Cobertura.xml)

          # Convert the line-rate to a percentage
          COVERAGE=$(echo "$LINE_RATE * 100" | bc -l)

          echo "Code Coverage: $COVERAGE%"

          # Check if the code coverage meets the threshold (e.g., 95%)
          if (( $(echo "$COVERAGE > 95" | bc -l) )); then
            echo "Coverage threshold met."
          else
            echo "Coverage threshold not met."
            exit 1
          fi

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: needs.build-and-test.outputs.coverage_passed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Pack the ToolBox project
        run: dotnet pack ToolBox --configuration Release --output ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json